version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build steps...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-container .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'